title = "Shane Curry"
description = "Shane Curry is a professional animator with 10 years experience in primetime television and streaming, building independent cartoons, rigs, systems, and Vector Based Animation Software."
canonical = "https://shanecurry.com/"
